FROM node:16-slim as node-builder

WORKDIR /app/

ARG DB_DOMAIN_NAME="db.domain.tld"
ENV DB_DOMAIN_NAME "${DB_DOMAIN_NAME}"

ARG NODE_ENV="production"
ENV NODE_ENV "${NODE_ENV}"

# Copy files for app
COPY . /app/

# Modify the app config to use environment variables
RUN sed -i "s/DB_DOMAIN_NAME/$DB_DOMAIN_NAME/g" /app/tirith-api/src/config/production.config.ts

RUN echo "Installing nest." && \
    npm install -g @nestjs/cli
RUN echo "Installing npm modules..." && \
    NODE_ENV=development npm install || exit 1 && \
    echo "npm modules installed." && \
    npm cache clean --force

# build and link palantir lib
RUN echo "installing tsc..." && \
    npm install -g typescript
RUN echo "building lib..." && \
    cd ./palantir-db && \
    tsc
RUN echo "linking lib..." && \
    npm link palantir-db -w tirith-api

# install over idk
RUN echo "Installing npm modules..." && \
    NODE_ENV=development npm install || exit 1 && \
    echo "npm modules installed." && \
    npm cache clean --force

# Build for production env
RUN echo "Building app...\n" && \
    npm run build || exit 1 && \
    echo "build was completed."

EXPOSE 3000

CMD ["sh", "-c", "node /app/tirith-api/dist/main.js"]