export * from './admin.service';
import { AdminService } from './admin.service';
export * from './announcements.service';
import { AnnouncementsService } from './announcements.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './awards.service';
import { AwardsService } from './awards.service';
export * from './cloud.service';
import { CloudService } from './cloud.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './emojis.service';
import { EmojisService } from './emojis.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './guilds.service';
import { GuildsService } from './guilds.service';
export * from './inventory.service';
import { InventoryService } from './inventory.service';
export * from './leagues.service';
import { LeaguesService } from './leagues.service';
export * from './lobbies.service';
import { LobbiesService } from './lobbies.service';
export * from './members.service';
import { MembersService } from './members.service';
export * from './oauth2.service';
import { Oauth2Service } from './oauth2.service';
export * from './scenes.service';
import { ScenesService } from './scenes.service';
export * from './sprites.service';
import { SpritesService } from './sprites.service';
export * from './themes.service';
import { ThemesService } from './themes.service';
export const APIS = [AdminService, AnnouncementsService, AuthService, AwardsService, CloudService, DefaultService, EmojisService, EventsService, GuildsService, InventoryService, LeaguesService, LobbiesService, MembersService, Oauth2Service, ScenesService, SpritesService, ThemesService];
