export * from './auth.service';
import { AuthService } from './auth.service';
export * from './awards.service';
import { AwardsService } from './awards.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './drops.service';
import { DropsService } from './drops.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './lobbies.service';
import { LobbiesService } from './lobbies.service';
export * from './members.service';
import { MembersService } from './members.service';
export * from './scenes.service';
import { ScenesService } from './scenes.service';
export * from './sprites.service';
import { SpritesService } from './sprites.service';
export const APIS = [AuthService, AwardsService, DefaultService, DropsService, EventsService, LobbiesService, MembersService, ScenesService, SpritesService];
