FROM node:16-slim as node-builder

WORKDIR /app/

# default env values for domain name
ARG API_DOMAIN_NAME="api.domain.tld"
ENV API_DOMAIN_NAME "${API_DOMAIN_NAME}"

ARG NODE_ENV="production"
ENV NODE_ENV "${NODE_ENV}"

# Copy files for app
COPY . /app/

RUN echo "Installing ng cli..." && \
    npm install -g @angular/cli
RUN echo "Installing npm modules..." && \
    NODE_ENV=development npm install || exit 1 && \
    echo "npm modules installed." && \
    npm cache clean --force


# Build for production env
RUN echo "Building app...\n" && \
    npm run build -w tirith-frontend || exit 1 && \
    echo "build was completed."

# Copy to cwd node (???)
RUN cp /app/tirith-frontend/dist /app/dist

# Copy the entrypoint script
COPY .docker/entrypoint-frontend.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 4000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["node", "/app/tirith-frontend/dist/Tirith/server/main.js"]