export default () => ({
    PORT: 3000,
    DISCORD_OAUTH_CLIENT_ID: '',
    DISCORD_OAUTH_CLIENT_SECRET: '',
    DISCORD_OAUTH_REDIRECT: '',
    DISCORD_API_TOKEN: '',
    GRPC_VALMAR_CHANNEL: ''
});