export default () => ({
    PORT: 3000,
    DB_HOST: "DB_DOMAIN_NAME_SED_PLACEHOLDER",
    DB_USER: "tirith",
    DB_PASSWORD: '',
    DISCORD_OAUTH_CLIENT_ID: 'DISCORD_OAUTH_CLIENT_ID_SED_PLACEHOLDER',
    DISCORD_OAUTH_CLIENT_SECRET: 'DISCORD_OAUTH_CLIENT_SECRET_SED_PLACEHOLDER',
    DISCORD_OAUTH_REDIRECT: 'DISCORD_OAUTH_REDIRECT_SED_PLACEHOLDER',
});
