export default () => ({
    PORT: 3000,
    DISCORD_OAUTH_CLIENT_ID: 'DISCORD_OAUTH_CLIENT_ID_SED_PLACEHOLDER',
    DISCORD_OAUTH_CLIENT_SECRET: 'DISCORD_OAUTH_CLIENT_SECRET_SED_PLACEHOLDER',
    DISCORD_OAUTH_REDIRECT: 'DISCORD_OAUTH_REDIRECT_SED_PLACEHOLDER',
    DISCORD_OAUTH_JWT_REDIRECT: 'DISCORD_OAUTH_JWT_REDIRECT_SED_PLACEHOLDER',
    DISCORD_API_TOKEN: 'DISCORD_API_TOKEN_SED_PLACEHOLDER',
    GRPC_VALMAR_CHANNEL: 'GRPC_CHANNEL_SED_PLACEHOLDER',
    GRPC_CONTENT_CHANNEL: 'CONTENT_GRPC_CHANNEL_SED_PLACEHOLDER',
    GRPC_EMOJI_CHANNEL: '',
});
