/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnnouncementDto { 
    /**
     * Announcement title
     */
    title: string;
    /**
     * Announcement content
     */
    content: string;
    /**
     * Version of typo which this targets
     */
    affectedTypoVersion?: string;
    /**
     * Announcement creation ms
     */
    date: string;
    /**
     * Announcement type
     */
    type: AnnouncementDto.TypeEnum;
    /**
     * Details of the announcement in markdown
     */
    details?: string;
}
export namespace AnnouncementDto {
    export type TypeEnum = 'Announcement' | 'Changelog';
    export const TypeEnum = {
        Announcement: 'Announcement' as TypeEnum,
        Changelog: 'Changelog' as TypeEnum
    };
}


