/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AwardDto { 
    /**
     * Award name
     */
    name: string;
    /**
     * Award unique ID
     */
    id: number;
    /**
     * Award description
     */
    description: string;
    /**
     * Award icon url
     */
    url: string;
    /**
     * Rarity level
     */
    rarity: number;
}

