/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CloudImageDto { 
    /**
     * Image name
     */
    name: string;
    /**
     * Image author
     */
    author: string;
    /**
     * Image creation timestamp ms
     */
    createdAt: string;
    /**
     * Image Id
     */
    id: string;
    /**
     * Meta Url
     */
    metaUrl: string;
    /**
     * Draw commands Url
     */
    commandsUrl: string;
    /**
     * Image Url
     */
    imageUrl: string;
}

