/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CloudSearchDto { 
    /**
     * The size of a single search result page
     */
    pageSize: number;
    /**
     * The current pagination index for given search criteria
     */
    page: number;
    /**
     * Exact name of the author
     */
    authorQuery?: string;
    /**
     * Exact language of the lobby
     */
    languageQuery?: string;
    /**
     * Oldest creation date filter
     */
    createdBeforeQuery?: string;
    /**
     * Most recent creation date filter
     */
    createdAfterQuery?: string;
    /**
     * Filter for private lobbies
     */
    createdInPrivateLobbyQuery?: boolean;
    /**
     * Filter for own drawings
     */
    isOwnQuery?: boolean;
    /**
     * Exact title of the drawing
     */
    titleQuery?: string;
}

