/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOAuth2ClientDto { 
    /**
     * The allowed OAuth2 redirect URIs for the OAuth2 client
     */
    redirectUris: Array<string>;
    /**
     * The scopes requested by the OAuth2 client
     */
    scopes: Array<string>;
    /**
     * The name of the OAuth2 client
     */
    name: string;
    /**
     * The audience of the OAuth2 client, typically the base url of the API that it accesses
     */
    audience: string;
}

