/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscordAuthenticationResultDto { 
    /**
     * The encrypted access token for the discord user that has authenticated using an auth code
     */
    encryptedAccessToken: string;
    /**
     * Whether the user already has a typo account or not
     */
    hasTypoAccount: boolean;
}

