/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DropDto { 
    /**
     * Drop ID
     */
    DropID: number;
    /**
     * Lobby where the drop has been caught
     */
    CaughtLobbyKey: string;
    /**
     * Discord User ID of the catcher
     */
    CaughtLobbyPlayerID: string;
    /**
     * Timestamp of the drop
     */
    ValidFrom: string;
    /**
     * Event Drop ID
     */
    EventDropID: number;
    /**
     * Response time of the catch
     */
    LeagueWeight: number;
}

