/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DropHistoryEntryDto } from './dropHistoryEntryDto';


export interface DropHistoryDto { 
    /**
     * Member typo id that this history belongs to
     */
    login: number;
    /**
     * Caught drops of the member in the history range
     */
    history: Array<DropHistoryEntryDto>;
}

