/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventDto } from './eventDto';


export interface EventDropDto { 
    /**
     * Unique event drop ID
     */
    id: number;
    /**
     * Drop name
     */
    name: string;
    /**
     * Drop URL
     */
    url: string;
    event: EventDto;
}

