/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventDto { 
    /**
     * Event name
     */
    name: string;
    /**
     * Event unique ID
     */
    id: number;
    /**
     * Event description
     */
    description: string;
    /**
     * Event start date
     */
    eventStart: string;
    /**
     * Event length in days
     */
    eventLength: number;
}

