/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebhookDto } from './webhookDto';


export interface GuildDto { 
    /**
     * The guild\'s ID
     */
    GuildID: string;
    /**
     * The guild\'s Palantir message channel ID
     */
    ChannelID: string;
    /**
     * The guild\'s Palantir message ID
     */
    MessageID: string;
    /**
     * The guild\'s Palantir token
     */
    ObserveToken: number;
    /**
     * The guild\'s name
     */
    GuildName: string;
    /**
     * The guild\'s post webhooks
     */
    Webhooks: Array<WebhookDto>;
}

