/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GuildInviteDto { 
    /**
     * Name of the server
     */
    name: string;
    /**
     * Palantir connection token of the server
     */
    token: number;
    /**
     * Current icon url of the guild
     */
    iconUrl: string;
    /**
     * Amount of connected members
     */
    connectedMembers: number;
}

