/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JwkDto { 
    /**
     * Key type, typically \'RSA\'
     */
    kty: string;
    /**
     * Key use, typically \'sig\' for signature
     */
    use: string;
    /**
     * Key ID, a unique identifier for the key
     */
    kid: string;
    /**
     * Algorithm used with the key, typically \'RS256\'
     */
    alg: string;
    /**
     * Modulus of the RSA key, base64url encoded
     */
    n: string;
    /**
     * Exponent of the RSA key, base64url encoded
     */
    e: string;
    /**
     * Private key is not exposed in JWKS
     */
    d?: string;
}

