/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeagueAverageTimeRanking { 
    /**
     * The palantir username of the participant
     */
    name: string;
    /**
     * The average catch response time of all caught league drops
     */
    averageTime: number;
}

