/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeagueScoreRanking { 
    /**
     * The palantir username of the participant
     */
    name: string;
    /**
     * Sum of the weighted scores of each league drop
     */
    score: number;
}

