/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LeagueScoreRanking } from './leagueScoreRanking';
import { LeagueAverageWeightRanking } from './leagueAverageWeightRanking';
import { LeagueCountRanking } from './leagueCountRanking';
import { LeagueAverageTimeRanking } from './leagueAverageTimeRanking';
import { LeagueStreakRanking } from './leagueStreakRanking';


export interface LeagueSeasonEvaluationDto { 
    /**
     * The year of the league season
     */
    year: number;
    /**
     * The month of the league season
     */
    month: number;
    /**
     * Ranking of all participants in category count
     */
    countRanking: Array<LeagueCountRanking>;
    /**
     * Ranking of all participants in category score
     */
    scoreRanking: Array<LeagueScoreRanking>;
    /**
     * Ranking of all participants in category streak
     */
    streakRanking: Array<LeagueStreakRanking>;
    /**
     * Ranking of all participants in category average weight
     */
    weightRanking: Array<LeagueAverageWeightRanking>;
    /**
     * Ranking of all participants in category average time
     */
    timeRanking: Array<LeagueAverageTimeRanking>;
}

