/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeagueSeasonMemberEvaluationDto { 
    /**
     * The year of the league season
     */
    year: number;
    /**
     * The month of the league season
     */
    month: number;
    /**
     * Sum of the weighted scores of each league drop
     */
    score: number;
    /**
     * Amount of league drops collected
     */
    count: number;
    /**
     * The maximum streak of caught league drops
     */
    maxStreak: number;
    /**
     * The current streak of caught league drops
     */
    currentStreak: number;
    /**
     * The average catch response time of all caught league drops
     */
    averageTime: number;
    /**
     * The average of weighted value of all caught league drops
     */
    averageWeight: number;
}

