/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LobbyPlayerDto { 
    /**
     * Player name
     */
    Name: string;
    /**
     * Player score
     */
    Score: number;
    /**
     * Whether the player is the drawer
     */
    Drawing: boolean;
    /**
     * Player join ID
     */
    LobbyPlayerID: number;
}

