/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LobbyPlayerDto { 
    /**
     * Player name
     */
    name: string;
    /**
     * Player score
     */
    score: number;
    /**
     * Whether the player is the drawer
     */
    drawing: boolean;
    /**
     * Player join ID
     */
    lobbyPlayerId: number;
}

