/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuildDto } from './guildDto';


export interface MemberDto { 
    /**
     * The member\'s plain bubbles
     */
    bubbles: number;
    /**
     * The member\'s regular drops
     */
    drops: number;
    /**
     * The member\'s sprite inventory
     */
    sprites: string;
    /**
     * The member\'s scene inventory
     */
    scenes: string;
    /**
     * The member\'s flag config
     */
    flags: number;
    /**
     * The member\'s rainbow sprite config
     */
    rainbowSprites: string;
    /**
     * The member\'s connected discord account id
     */
    discordID: string;
    /**
     * The member\'s palantir accunt user name
     */
    userName: string;
    /**
     * The member\'s palantir identification
     */
    userLogin: string;
    /**
     * The member\'s palantir identification
     */
    guilds: Array<GuildDto>;
    /**
     * The raw database member result
     */
    rawMember: object;
    /**
     * Enum array containing the flags of the member
     */
    memberFlags: Array<MemberDto.MemberFlagsEnum>;
}
export namespace MemberDto {
    export type MemberFlagsEnum = 'Admin' | 'Moderator' | 'Patron' | 'Patronizer' | 'Booster' | 'DropBan' | 'PermaBan' | 'Beta' | 'BubbleFarming' | 'UnlimitedCloud' | 'ContentModerator' | 'EmojiManagement';
    export const MemberFlagsEnum = {
        Admin: 'Admin' as MemberFlagsEnum,
        Moderator: 'Moderator' as MemberFlagsEnum,
        Patron: 'Patron' as MemberFlagsEnum,
        Patronizer: 'Patronizer' as MemberFlagsEnum,
        Booster: 'Booster' as MemberFlagsEnum,
        DropBan: 'DropBan' as MemberFlagsEnum,
        PermaBan: 'PermaBan' as MemberFlagsEnum,
        Beta: 'Beta' as MemberFlagsEnum,
        BubbleFarming: 'BubbleFarming' as MemberFlagsEnum,
        UnlimitedCloud: 'UnlimitedCloud' as MemberFlagsEnum,
        ContentModerator: 'ContentModerator' as MemberFlagsEnum,
        EmojiManagement: 'EmojiManagement' as MemberFlagsEnum
    };
}


