/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberSearchDto { 
    /**
     * The member\'s palantir accunt user name
     */
    userName: string;
    /**
     * The member\'s palantir identification
     */
    userLogin: string;
    /**
     * The raw database member result
     */
    rawMember: object;
}

