/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuildDto } from './guildDto';


export interface MemberWebhookDto { 
    /**
     * The webhook name
     */
    Name: string;
    Guild: GuildDto;
}

