/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2AuthorizationCodeExchangeDto { 
    /**
     * The authorization code received from the OAuth2 client
     */
    code: string;
    /**
     * The client ID of the OAuth2 client
     */
    client_id: number;
    /**
     * The typo ID of the user requesting the exchange
     */
    grant_type: string;
}

