/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2AccessTokenResponseDto { 
    /**
     * The issued jwt access token for member and client
     */
    access_token: string;
    /**
     * The returned token type
     */
    token_type: string;
    /**
     * The returned token type kind for token-exchange grant
     */
    issued_token_type?: string;
    /**
     * The expiry time in seconds
     */
    expires_in: number;
    /**
     * The scope of the generated token
     */
    scope: string;
}

