/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2TokenExchangeDto { 
    /**
     * The oauth2 grant type
     */
    grant_type: string;
    /**
     * An authorization code received from the OAuth2 client, required for grant_type=code
     */
    code?: string;
    /**
     * The client ID of the OAuth2 client, required for grant_type=code
     */
    client_id?: number;
    /**
     * An access token to be exchanged, required for grant_type=token-exchange
     */
    subject_token?: string;
    /**
     * The type of the subject token, required for grant_type=token-exchange
     */
    subject_token_type?: string;
    /**
     * The requested audience of the subject token, required for grant_type=token-exchange
     */
    audience?: string;
}

