/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTypoAccountOptionsDto } from './createTypoAccountOptionsDto';


export interface OAuth2AuthenticationDto { 
    /**
     * The encrypted access token which had previously been received in the preauthorize step
     */
    discordEncryptedAccessToken: string;
    /**
     * The client ID of the application requesting authentication
     */
    clientId: number;
    createAccountOptions?: CreateTypoAccountOptionsDto;
}

