/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2ClientDto { 
    /**
     * The client ID of the OAuth2 client
     */
    clientId: number;
    /**
     * The redirect URI for the OAuth2 client
     */
    redirectUri: string;
    /**
     * The scopes requested by the OAuth2 client
     */
    scopes: Array<string>;
    /**
     * The name of the OAuth2 client 
     */
    name: string;
    /**
     * Whether the client has been verified by typo
     */
    verified: boolean;
    /**
     * Token expiry time in seconds
     */
    tokenExpiry: number;
    /**
     * The typo id of the client owner
     */
    ownerTypoId: number;
}

