/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OnlineLobbySkribblDetailsDto } from './onlineLobbySkribblDetailsDto';
import { OnlineLobbyTypoPlayerDto } from './onlineLobbyTypoPlayerDto';


export interface OnlineLobbyDto { 
    /**
     * Lobby description
     */
    description: string;
    /**
     * Lobby las updated timestamp
     */
    lastUpdated: string;
    /**
     * Lobby typo ownership claim
     */
    ownershipClaim: string;
    skribblDetails: OnlineLobbySkribblDetailsDto;
    /**
     * Lobby palantir details
     */
    typoPlayers: Array<OnlineLobbyTypoPlayerDto>;
}

