/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LobbyPlayerDto } from './lobbyPlayerDto';


export interface OnlineLobbySkribblDetailsDto { 
    /**
     * Lobby skribbl ID (part of the link)
     */
    id: string;
    /**
     * Indicator if the lobby is private
     */
    _private: boolean;
    /**
     * The lobby\'s current round
     */
    round: number;
    /**
     * The lobby\'s current players
     */
    players: Array<LobbyPlayerDto>;
    /**
     * The lobby language
     */
    language: string;
}

