/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OpenIdConfigurationDto { 
    /**
     * Issuer server identifier
     */
    issuer: string;
    /**
     * JWKS URI for public key used to verify signatures
     */
    jwks_uri: string;
    /**
     * Typo OAuth2 authorization endpoint
     */
    authorization_endpoint: string;
    /**
     * Typo OAuth2 token endpoint
     */
    token_endpoint: string;
    /**
     * Typo user profile claims endpoint
     */
    userinfo_endpoint: string;
    /**
     * Empty scopes; scopes are assigned by client
     */
    scopes_supported: Array<string>;
    /**
     * Supported token claims
     */
    claims_supported: Array<string>;
    /**
     * Only code flow supported
     */
    response_types_supported: Array<string>;
    /**
     * Only code flow supported
     */
    grant_types_supported: Array<string>;
    /**
     * Only public subject types
     */
    subject_types_supported: Array<string>;
    /**
     * RS256 Signing algorithms for ID tokens
     */
    id_token_signing_alg_values_supported: Array<string>;
    /**
     * No code challenge methods supported
     */
    code_challenge_methods_supported: Array<string>;
    /**
     * No token endpoint authentication methods supported
     */
    token_endpoint_auth_methods_supported: Array<string>;
}

