/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PalantirLobbyDto { 
    /**
     * Lobby description
     */
    Description: string;
    /**
     * Lobby invite encrypted
     */
    Key: string;
    /**
     * Lobby unique id
     */
    ID: string;
    /**
     * Lobby visibility restriction
     */
    Restriction: string;
}

