/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostImageDto { 
    /**
     * Image title
     */
    title: string;
    /**
     * Image author
     */
    author: string;
    /**
     * Image poster name
     */
    posterName: string;
    /**
     * Post only image without embed
     */
    onlyImage: boolean;
    /**
     * Base64 url representation of the image
     */
    imageBase64: string;
}

