/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreauthenticateDiscordOauth2CodeDto { 
    /**
     * The discord authorization code used to exchange for a discord access token
     */
    authorizationCode: string;
}

