/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicMemberDto { 
    /**
     * The member\'s connected discord account id
     */
    discordID: string;
    /**
     * The member\'s palantir accunt user name
     */
    userName: string;
    /**
     * DEPRECATED. Use TypoId instead.
     */
    userLogin: string;
    /**
     * The member\'s typo unique identification
     */
    typoId: number;
    /**
     * Enum array containing the flags of the member
     */
    memberFlags: Array<PublicMemberDto.MemberFlagsEnum>;
}
export namespace PublicMemberDto {
    export type MemberFlagsEnum = 'Admin' | 'Moderator' | 'Patron' | 'Patronizer' | 'Booster' | 'DropBan' | 'PermaBan' | 'Beta' | 'BubbleFarming' | 'UnlimitedCloud' | 'ContentModerator' | 'EmojiManagement';
    export const MemberFlagsEnum = {
        Admin: 'Admin' as MemberFlagsEnum,
        Moderator: 'Moderator' as MemberFlagsEnum,
        Patron: 'Patron' as MemberFlagsEnum,
        Patronizer: 'Patronizer' as MemberFlagsEnum,
        Booster: 'Booster' as MemberFlagsEnum,
        DropBan: 'DropBan' as MemberFlagsEnum,
        PermaBan: 'PermaBan' as MemberFlagsEnum,
        Beta: 'Beta' as MemberFlagsEnum,
        BubbleFarming: 'BubbleFarming' as MemberFlagsEnum,
        UnlimitedCloud: 'UnlimitedCloud' as MemberFlagsEnum,
        ContentModerator: 'ContentModerator' as MemberFlagsEnum,
        EmojiManagement: 'EmojiManagement' as MemberFlagsEnum
    };
}


