/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationRequest { 
    /**
     * The discord oauth authorization code
     */
    code: string;
    /**
     * The flag whether the user wants to conenct to the typo server
     */
    connectTypo: boolean;
}

