/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LobbyPlayerDto } from './lobbyPlayerDto';


export interface ReportsResponseDto { 
    /**
     * Lobby description
     */
    Description: string;
    /**
     * Lobby invite encrypted
     */
    Key: string;
    /**
     * Lobby unique id
     */
    ID: string;
    /**
     * Lobby visibility restriction
     */
    Restriction: string;
    /**
     * Guild id which the report targets
     */
    GuildID: string;
    /**
     * Lobby players
     */
    Players: Array<LobbyPlayerDto>;
}

