/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SceneInventoryItemDto { 
    /**
     * A scene Id
     */
    sceneId: number;
    /**
     * A scene theme shift identification
     */
    sceneShift?: number;
}

