/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpriteInventoryDto { 
    /**
     * A sprite slot number, starting at 1, or undefined if sprite is not active
     */
    slot?: number;
    /**
     * A sprite Id
     */
    spriteId: number;
    /**
     * A rainbow sprite color shift
     */
    colorShift?: number;
}

