/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpriteSlotDto { 
    /**
     * A sprite slot number, starting at 1
     */
    slotId: number;
    /**
     * The target sprite Id, undefined to use no sprite
     */
    spriteId?: number;
}

