/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentication.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpriteSlotDto } from './spriteSlotDto';


export interface SpriteComboDto { 
    /**
     * The sprite slots that will be the new user sprite combo
     */
    slots: Array<SpriteSlotDto>;
}

