/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponse { 
    /**
     * The acces token to log in to the new account
     */
    accessToken: string;
    /**
     * The discord user id of the oauth code
     */
    userId: string;
    /**
     * The discord user name of the oauth code
     */
    userName: string;
}

