/**
 * Skribbl Typo API
 * Skribbl typo admin and auth api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WebhookDto { 
    /**
     * The webhook name
     */
    Name: string;
    /**
     * The webhook\'s guild name
     */
    Guild: string;
    /**
     * The webhook URL
     */
    URL: string;
}

