name: build-frontend

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-frontend.yml'
      - 'tirith-frontend/**'
      - '.docker/Dockerfile-frontend'
      - '.docker/entrypoint-frontend.sh'

env:
  IMAGE_NAME: tirith-frontend
  DOCKERFILE_PATH: ./.docker/Dockerfile-frontend

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/toobeeh/tirith/${{ env.IMAGE_NAME }}:latest
