name: build

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: tirith-api
  DOCKERFILE_PATH: ./Dockerfile-api

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/toobeeh/tirith/${{ env.IMAGE_NAME }}:latest
